SELECT TOP 20 * FROM customer;

-- Q1. What is the total revenue generated by mle vs. female customers?
Select gender, sum(purchase_amount) as revenue
from customer
GROUP BY Gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount>=(Select avg(purchase_amount) as p from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, avg(review_rating) as a
FROM customer
group by item_purchased
Order by avg(review_rating) desc

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
Select shipping_type, avg(purchase_amount) as a
from customer where shipping_type in ('Express','Standard')
Group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, count(customer_id)as customer_count, sum(purchase_amount) as total_spend, avg(purchase_amount) as avg_spend
from customer
Group by subscription_status
order by avg_spend, total_spend desc

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased, 100 * Sum(case when discount_applied = 'Yes' then 1 else 0 End)/count (*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (select customer_id, previous_purchases,  
Case when previous_purchases < 2 then 'New' 
when previous_purchases BETWEEN 2 and 10 then 'Returning' else 'Loyal' end as Segment
from customer)
Select Segment, count(*) as 'Number of Customers'
from customer_type
group by Segment

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as ( select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased)
Select category, item_purchased, item_rank, total_orders
from item_counts
where item_rank <=3

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
Select age_group, sum(purchase_amount) as Total_Contribution
from customer
group by age_group
order by Total_Contribution desc



